options:
  project-root: ../implementation # root is the DH Go implementation directory
  reports-dir: ../argot-proofs/argot-reports
  log-level: 3 # log at info level (3), debug level is 4 and trace is 5
  use-escape-analysis: true
  escape-config: ../argot-proofs/escape-config.json
  report-paths: true
  silence-warn: false # TODO fix escape warning for (*encoding/base64.Encoding).DecodeString during taint analysis
  analysis-options:
    max-alarms: 2

targets:
  - name: dh
    files:
      - main.go

pointer-config:
  # The following function's effect on aliasing is ignored; it creates too many false positives.
  # Otherwise they may cause most error values to be aliased.
  unsafe-no-effect-functions:
    - fmt.Errorf
    - .*.Errorf

immutability-problems:
  # All methods with the core invariant
  - tag: diodon-dh-core-invariant
    description: "Diodon: DH core invariant maintenance proof"
    severity: HIGH
    targets:
      - dh
    values:
      - package: dh-gobra/initiator
        method: ProduceHsMsg1
        context: 0
      - package: dh-gobra/initiator
        method: ProcessHsMsg2
        context: 0
      - package: dh-gobra/initiator
        method: ProduceHsMsg3
        context: 0
      - package: dh-gobra/initiator
        method: ProcessTransportMsg
        context: 0
      - package: dh-gobra/initiator
        method: ProduceTransportMsg
        context: 0
    filters:
      # core: verified by Gobra
      - package: dh-gobra/initiator
        method: .*
      # core: verified by Gobra
      - package: dh-gobra/library
        method: .*

diodon-pass-through-problems:
  - tag: diodon-dh-core-invariant-passthrough
    description: "Diodon: DH core invariant maintenance pass-through proof"
    severity: HIGH
    targets:
      - dh
    app-functions:
      - package: dh-gobra.*
        method: .*
      - package: command-line-arguments
        method: .*
    core-functions:
      - package: dh-gobra/initiator
        method: .*
      - package: dh-gobra/library
        method: .*
    core-alloc-function:
      package: dh-gobra/initiator
      method: NewInitiator
      return-indices: [0]
    core-api-functions:
      - package: dh-gobra/initiator
        method: NewInitiator
      - package: dh-gobra/initiator
        method: ProduceHsMsg1
      - package: dh-gobra/initiator
        method: ProduceHsMsg3
      - package: dh-gobra/initiator
        method: ProcessTransportMsg
      - package: dh-gobra/initiator
        method: ProduceTransportMsg
    app-access-filters:
      # - package: internal/byteorder
      #   method: BeUint64

dataflow-problems:
  summarize-on-demand: true
  user-specs:
    - ../argot-proofs/std-specs.json
    - ../argot-proofs/dependency-specs.json
  field-sensitive-funcs:
    - .*

  taint-tracking:
    - tag: diodon-dh-io-independence
      description: "Diodon: DH I/O independence proof"
      targets:
        - dh
      severity: HIGH
      filters:
        - type: error$ # We do not consider errors as tainted
      fail-on-implicit-flow: true # handle information flow
      sources:
        - package: command-line-arguments
          method: parsePrivateKey$
        - package: dh-gobra/library
          method: createNonce$
      sanitizers:
        - package: dh-gobra/library
          method: PerformVirtualOutputOperation
        - package: command-line-arguments
          method: sanitizeStr$
      sinks:
        - package: dh-gobra/library
          method: PerformVirtualInputOperation
        - interface: T$
          package: .*log$
        - method: Info.*$
          package: .*log$
        - method: Debug.*$
          package: .*log$
        - method: Trace.*$
          package: .*log$
        - method: Warn.*$
          package: .*log$
        - method: Warn.*$
          package: .*log$
        - method: Error.*$
          package: .*log$
        - method: Critical.*$
          package: .*log$
        - method: SetFlags$
          package: log$
        - method: SetOutput$
          package: log$
        - method: Dial$
          package: net$
        - method: DialIP$
          package: net$
        - method: DialTCP$
          package: net$
        - method: DialTimeout$
          package: net$
        - method: DialUDP$
          package: net$
        - method: DialUnix$
          package: net$
        - method: FileConn$
          package: net$
        - method: FileListener$
          package: net$
        - method: FilePacketConn$
          package: net$
        - method: Listen$
          package: net$
        - method: ListenIP$
          package: net$
        - method: ListenMulticastUDP$
          package: net$
        - method: ListenPacket$
          package: net$
        - method: ListenTCP$
          package: net$
        - method: ListenUDP$
          package: net$
        - method: ListenUnix$
          package: net$
        - method: ListenUnixgram$
          package: net$
        - method: LookupAddr$
          package: net$
        - method: LookupCNAME$
          package: net$
        - method: LookupHost$
          package: net$
        - method: LookupIP$
          package: net$
        - method: LookupMX$
          package: net$
        - method: LookupNS$
          package: net$
        - method: LookupPort$
          package: net$
        - method: LookupSRV$
          package: net$
        - method: LookupTXT$
          package: net$
        - method: ResolveIPAddr$
          package: net$
        - method: ResolveTCPAddr$
          package: net$
        - method: ResolveUDPAddr$
          package: net$
        - method: ResolveUnixAddr$
          package: net$
        - method: Chdir$
          package: os$
        - method: Chmod$
          package: os$
        - method: Chown$
          package: os$
        - method: Chtimes$
          package: os$
        - method: Clearenv$
          package: os$
        - method: Create$
          package: os$
        - method: CreateTemp$
          package: os$
        - method: DirFS$
          package: os$
        - method: Lchown$
          package: os$
        - method: Link$
          package: os$
        - method: Lstat$
          package: os$
        - method: Mkdir$
          package: os$
        - method: MkdirAll$
          package: os$
        - method: MkdirTemp$
          package: os$
        - method: NewFile$
          package: os$
        - method: Open$
          package: os$
        - method: OpenFile$
          package: os$
        - method: Pipe$
          package: os$
        - method: ReadDir$
          package: os$
        - method: ReadFile$
          package: os$
        - method: Readlink$
          package: os$
        - method: Remove$
          package: os$
        - method: RemoveAll$
          package: os$
        - method: Rename$
          package: os$
        - method: SameFile$
          package: os$
        - method: Setenv$
          package: os$
        - method: Stat$
          package: os$
        - method: Symlink$
          package: os$
        - method: Truncate$
          package: os$
        - method: Unsetenv$
          package: os$
        - method: WriteFile$
          package: os$
        - method: Chdir$
          package: os$
        - method: Chmod$
          package: os$
        - method: Chown$
          package: os$
        - method: Close$
          package: os$
        - method: Fd$
          package: os$
        - method: Name$
          package: os$
        - method: Read$
          package: os$
        - method: ReadAt$
          package: os$
        - method: ReadDir$
          package: os$
        - method: ReadFrom$
          package: os$
        - method: Readdir$
          package: os$
        - method: Readdirnames$
          package: os$
        - method: Seek$
          package: os$
        - method: SetDeadline$
          package: os$
        - method: SetReadDeadline$
          package: os$
        - method: SetWriteDeadline$
          package: os$
        - method: Stat$
          package: os$
        - method: Sync$
          package: os$
        - method: SyscallConn$
          package: os$
        - method: Truncate$
          package: os$
        - method: Write$
          package: os$
        - method: WriteAt$
          package: os$
        - method: WriteString$
          package: os$
        - method: IsDir$
          package: os$
        - method: ModTime$
          package: os$
        - method: Mode$
          package: os$
        - method: Name$
          package: os$
        - method: Size$
          package: os$
        - method: Sys$
          package: os$
        - method: Name$
          package: os$
        - method: LookPath$
          package: os/exec$
        - method: Open$
          package: plugin$
        - method: WriteHeapDump$
          package: runtime/debug$
        - method: .*
          package: os$
        - method: .*
          package: os/exec$
        - method: .*
          package: net$
        - method: .*
          package: net/http$
        - method: .*
          package: unsafe$
        - method: Breakpoint$
          package: runtime$
        - method: CPUProfile$
          package: runtime$
        - method: Goexit$
          package: runtime$
        - method: SetCgoTraceback$
          package: runtime$
        - method: UnlockOSThread$
          package: runtime$
        - method: SetGCPercent$
          package: runtime/debug$
        - method: SetMaxStack$
          package: runtime/debug$
        - method: SetMaxThreads$
          package: runtime/debug$
        - method: SetPanicOnFault$
          package: runtime/debug$
        - method: Read$
          package: runtime/metrics$
        - method: SetFinalizer$
          package: runtime$
        - method: .*
          package: reflect$
        - method: .*
          package: runtime$
        - method: .*
          package: runtime/cgo$
        - method: .*
          package: runtime/debug$
        - method: .*
          package: runtime/pprof$
        - method: .*
          package: os/signal$
        - method: Print.*
          package: fmt$
