name: Artifact

# creates the artifact docker image and
# - verifies the Tamarin model
# - TODO

on:
  push:

env:
  IMAGE_ARTIFACT_NAME: diodon-artifact-image

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Create Image ID
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_ID=ghcr.io/$REPO_OWNER/diodon-artifact" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Image version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo "IMAGE_TAG=${{ env.IMAGE_ID }}:$VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          file: docker/Dockerfile
          tags: ${{ env.IMAGE_TAG }}
          labels: "runnumber=${{ github.run_id }}"
          push: false
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_ARTIFACT_NAME }}
          path: /tmp/image.tar

      - name: Set output
        run: echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT


  test:
    name: test - ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      # tests should not be stopped when they fail on one of the OSes:
      fail-fast: false
      matrix:
        name: ["Verify protocol model"]
        include:
          - name: "Verify protocol model"
            command: "/gobra/verify-model.sh"
    timeout-minutes: 15
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_ARTIFACT_NAME }}
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/image.tar

      # - name: Verify protocol model
      #  run: docker run --entrypoint "/bin/bash" ${{ needs.build.outputs.IMAGE_TAG }} -c "cp -r model-orig/. model/; ${{ matrix.command }}"


  publish:
    runs-on: ubuntu-latest
    needs: [build, test]
    timeout-minutes: 1
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_ARTIFACT_NAME }}
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/image.tar

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push --label "runnumber=${{ github.run_id }}" ${{ needs.build.outputs.IMAGE_TAG }}


  cleanup:
    runs-on: ubuntu-latest
    needs: publish
    if: always()
    steps:
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v4
        with:
          name: ${{ env.IMAGE_ARTIFACT_NAME }}
          failOnError: false
